
%show maze solving instructions at the start of the experiment
function [flipTime] = showInstructions(window)

    Screen('FillRect', window, 127);
    textColour = [0, 0, 0, 255];
    Screen('TextFont', window, 'Times');
    Screen('TextSize', window, 25); 
    strIntr = ['Welcome to our study! \n\nIT IS IMPORTANT TO READ THE INSTRUCTIONS CAREFULLY\n\n' ...
        'Escape the maze in AS FEW MOVES AS POSSIBLE by reaching the exit (the red square).\n\n'...
        'Blue squares are walls. You cannot see through the walls. The squares you cannot see yet are black.\n\n'...
        'The exit is EQUALLY LIKELY to be behind ANY of the black squares.\n\n '...
        'In the end you will see how many steps you took compared to others.\n\n'...
        'The experimenter will demo the task, followed by a short practice.\n\n' ...
        'Press any key to start...'...
        ];
    DrawFormattedText( window, strIntr, 'center', 190, textColour);
    flipTime=Screen('Flip',window);
end